// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  GetItemData,
  GetItemErrors,
  GetItemResponses,
  HealthzData,
  HealthzResponses,
  HelloData,
  HelloResponses,
  ListItemsData,
  ListItemsErrors,
  ListItemsResponses,
  MeData,
  MeResponses,
  RegisterTokenData,
  RegisterTokenErrors,
  RegisterTokenResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Healthz
 */
export const healthz = <ThrowOnError extends boolean = false>(
  options?: Options<HealthzData, ThrowOnError>,
): RequestResult<HealthzResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({
    url: "/healthz",
    ...options,
  });

/**
 * Hello
 */
export const hello = <ThrowOnError extends boolean = false>(
  options?: Options<HelloData, ThrowOnError>,
): RequestResult<HelloResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HelloResponses, unknown, ThrowOnError>({
    url: "/v1/hello",
    ...options,
  });

/**
 * List Items
 */
export const listItems = <ThrowOnError extends boolean = false>(
  options?: Options<ListItemsData, ThrowOnError>,
): RequestResult<ListItemsResponses, ListItemsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListItemsResponses, ListItemsErrors, ThrowOnError>({
    url: "/v1/items",
    ...options,
  });

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
): RequestResult<CreateItemResponses, CreateItemErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
    url: "/v1/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
): RequestResult<DeleteItemResponses, DeleteItemErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteItemResponses, DeleteItemErrors, ThrowOnError>({
    url: "/v1/items/{item_id}",
    ...options,
  });

/**
 * Get Item
 */
export const getItem = <ThrowOnError extends boolean = false>(
  options: Options<GetItemData, ThrowOnError>,
): RequestResult<GetItemResponses, GetItemErrors, ThrowOnError> =>
  (options.client ?? client).get<GetItemResponses, GetItemErrors, ThrowOnError>({
    url: "/v1/items/{item_id}",
    ...options,
  });

/**
 * Update Item
 */
export const updateItem = <ThrowOnError extends boolean = false>(
  options: Options<UpdateItemData, ThrowOnError>,
): RequestResult<UpdateItemResponses, UpdateItemErrors, ThrowOnError> =>
  (options.client ?? client).patch<UpdateItemResponses, UpdateItemErrors, ThrowOnError>({
    url: "/v1/items/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(
  options?: Options<MeData, ThrowOnError>,
): RequestResult<MeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
    url: "/v1/me",
    ...options,
  });

/**
 * Register Token
 */
export const registerToken = <ThrowOnError extends boolean = false>(
  options: Options<RegisterTokenData, ThrowOnError>,
): RequestResult<RegisterTokenResponses, RegisterTokenErrors, ThrowOnError> =>
  (options.client ?? client).post<RegisterTokenResponses, RegisterTokenErrors, ThrowOnError>({
    url: "/v1/push-tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
