// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      title: "Detail",
      type: "array",
    },
  },
  title: "HTTPValidationError",
  type: "object",
} as const;

export const HealthSchema = {
  properties: {
    status: {
      title: "Status",
      type: "string",
    },
  },
  required: ["status"],
  title: "Health",
  type: "object",
} as const;

export const HelloSchema = {
  properties: {
    message: {
      title: "Message",
      type: "string",
    },
  },
  required: ["message"],
  title: "Hello",
  type: "object",
} as const;

export const ItemCreateSchema = {
  properties: {
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    title: {
      title: "Title",
      type: "string",
    },
  },
  required: ["title"],
  title: "ItemCreate",
  type: "object",
} as const;

export const ItemReadSchema = {
  properties: {
    created_at: {
      format: "date-time",
      title: "Created At",
      type: "string",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    id: {
      format: "uuid",
      title: "Id",
      type: "string",
    },
    owner_id: {
      title: "Owner Id",
      type: "string",
    },
    title: {
      title: "Title",
      type: "string",
    },
    updated_at: {
      format: "date-time",
      title: "Updated At",
      type: "string",
    },
  },
  required: ["id", "title", "description", "owner_id", "created_at", "updated_at"],
  title: "ItemRead",
  type: "object",
} as const;

export const ItemUpdateSchema = {
  properties: {
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Title",
    },
  },
  title: "ItemUpdate",
  type: "object",
} as const;

export const MeReadSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
    id: {
      title: "Id",
      type: "string",
    },
  },
  required: ["id"],
  title: "MeRead",
  type: "object",
} as const;

export const Page_ItemRead_Schema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/ItemRead",
      },
      title: "Items",
      type: "array",
    },
    next_cursor: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Next Cursor",
    },
  },
  required: ["items"],
  title: "Page[ItemRead]",
  type: "object",
} as const;

export const ProblemSchema = {
  description: "RFC 9457 problem+json body — declared so it types into the OpenAPI schema.",
  properties: {
    detail: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Detail",
    },
    instance: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Instance",
    },
    status: {
      title: "Status",
      type: "integer",
    },
    title: {
      title: "Title",
      type: "string",
    },
    type: {
      default: "about:blank",
      title: "Type",
      type: "string",
    },
  },
  required: ["title", "status"],
  title: "Problem",
  type: "object",
} as const;

export const PushTokenCreateSchema = {
  properties: {
    device_id: {
      title: "Device Id",
      type: "string",
    },
    expo_token: {
      title: "Expo Token",
      type: "string",
    },
  },
  required: ["device_id", "expo_token"],
  title: "PushTokenCreate",
  type: "object",
} as const;

export const PushTokenReadSchema = {
  properties: {
    device_id: {
      title: "Device Id",
      type: "string",
    },
    expo_token: {
      title: "Expo Token",
      type: "string",
    },
    id: {
      format: "uuid",
      title: "Id",
      type: "string",
    },
  },
  required: ["id", "device_id", "expo_token"],
  title: "PushTokenRead",
  type: "object",
} as const;

export const ValidationErrorSchema = {
  properties: {
    ctx: {
      title: "Context",
      type: "object",
    },
    input: {
      title: "Input",
    },
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      title: "Location",
      type: "array",
    },
    msg: {
      title: "Message",
      type: "string",
    },
    type: {
      title: "Error Type",
      type: "string",
    },
  },
  required: ["loc", "msg", "type"],
  title: "ValidationError",
  type: "object",
} as const;
