// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createItem,
  deleteItem,
  getItem,
  healthz,
  hello,
  listItems,
  me,
  type Options,
  registerToken,
  updateItem,
} from "../sdk.gen";
import type {
  CreateItemData,
  CreateItemError,
  CreateItemResponse,
  DeleteItemData,
  DeleteItemError,
  DeleteItemResponse,
  GetItemData,
  GetItemError,
  GetItemResponse,
  HealthzData,
  HealthzResponse,
  HelloData,
  HelloResponse,
  ListItemsData,
  ListItemsError,
  ListItemsResponse,
  MeData,
  MeResponse,
  RegisterTokenData,
  RegisterTokenError,
  RegisterTokenResponse,
  UpdateItemData,
  UpdateItemError,
  UpdateItemResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthzQueryKey = (options?: Options<HealthzData>) =>
  createQueryKey("healthz", options);

/**
 * Healthz
 */
export const healthzOptions = (options?: Options<HealthzData>) =>
  queryOptions<HealthzResponse, DefaultError, HealthzResponse, ReturnType<typeof healthzQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthz({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthzQueryKey(options),
  });

export const helloQueryKey = (options?: Options<HelloData>) => createQueryKey("hello", options);

/**
 * Hello
 */
export const helloOptions = (options?: Options<HelloData>) =>
  queryOptions<HelloResponse, DefaultError, HelloResponse, ReturnType<typeof helloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await hello({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: helloQueryKey(options),
  });

export const listItemsQueryKey = (options?: Options<ListItemsData>) =>
  createQueryKey("listItems", options);

/**
 * List Items
 */
export const listItemsOptions = (options?: Options<ListItemsData>) =>
  queryOptions<
    ListItemsResponse,
    ListItemsError,
    ListItemsResponse,
    ReturnType<typeof listItemsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listItems({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listItemsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listItemsInfiniteQueryKey = (
  options?: Options<ListItemsData>,
): QueryKey<Options<ListItemsData>> => createQueryKey("listItems", options, true);

/**
 * List Items
 */
export const listItemsInfiniteOptions = (options?: Options<ListItemsData>) => {
  const opts = infiniteQueryOptions<
    ListItemsResponse,
    ListItemsError,
    InfiniteData<ListItemsResponse>,
    QueryKey<Options<ListItemsData>>,
    string | null | Pick<QueryKey<Options<ListItemsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListItemsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listItems({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listItemsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Item
 */
export const createItemMutation = (
  options?: Partial<Options<CreateItemData>>,
): UseMutationOptions<CreateItemResponse, CreateItemError, Options<CreateItemData>> => {
  const mutationOptions: UseMutationOptions<
    CreateItemResponse,
    CreateItemError,
    Options<CreateItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Item
 */
export const deleteItemMutation = (
  options?: Partial<Options<DeleteItemData>>,
): UseMutationOptions<DeleteItemResponse, DeleteItemError, Options<DeleteItemData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteItemResponse,
    DeleteItemError,
    Options<DeleteItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getItemQueryKey = (options: Options<GetItemData>) =>
  createQueryKey("getItem", options);

/**
 * Get Item
 */
export const getItemOptions = (options: Options<GetItemData>) =>
  queryOptions<GetItemResponse, GetItemError, GetItemResponse, ReturnType<typeof getItemQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getItem({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getItemQueryKey(options),
  });

/**
 * Update Item
 */
export const updateItemMutation = (
  options?: Partial<Options<UpdateItemData>>,
): UseMutationOptions<UpdateItemResponse, UpdateItemError, Options<UpdateItemData>> => {
  const mutationOptions: UseMutationOptions<
    UpdateItemResponse,
    UpdateItemError,
    Options<UpdateItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey("me", options);

/**
 * Me
 */
export const meOptions = (options?: Options<MeData>) =>
  queryOptions<MeResponse, DefaultError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await me({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: meQueryKey(options),
  });

/**
 * Register Token
 */
export const registerTokenMutation = (
  options?: Partial<Options<RegisterTokenData>>,
): UseMutationOptions<RegisterTokenResponse, RegisterTokenError, Options<RegisterTokenData>> => {
  const mutationOptions: UseMutationOptions<
    RegisterTokenResponse,
    RegisterTokenError,
    Options<RegisterTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await registerToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
